pattern_generator:
    update_rate: 10 # [Hz]
    number_of_steps_needed: 5
    republish_complete_step_plan: False

joystick:
    x:      { axis: 1, thresh: 0.1, min: -1.0, max: 1.0, zero: 0.0, invert: False }
    y:      { axis: 0, thresh: 0.1, min: -1.0, max: 1.0, zero: 0.0, invert: False }
    yaw:    { axis: 3, thresh: 0.1, min: -1.0, max: 1.0, zero: 0.0, invert: False }
    enable: { axis: 2, thresh: 0.5, min: -2.0, max: 0.0, zero: 1.0, invert: False }
