robot_name: Nao

world_frame_id: /world

#Not sure what to put here yet -tg 7 March 2017
#Trying reasonable values for upper body 9 March 2017
### upper body settings ########################################################
upper_body:
  size: {x: 0.311, y: 0.275, z: 0.574} # [m]
  #No idea what the origin_shift should be, but 0,0,0 seems reasonable
  origin_shift: {x: 0.0, y: 0.00, z: 0.00} # [m], transformation from center to shifted frame

### Footstep parameterization for the Aldebaran Robotics Nao humanoid #########

### footstep settings #########################################################
#A Hornung's parameters for Nao (footsteps_nao_navigation.yaml)
# Footstep displacement vectors (in meter / rad)
# NOTE: not all footsteps within the max values can be performed since the
#       boundary of allowd footsteps is an ellipse
# WARNING: data type has to be float since integers will cause an exception
#footsteps:
#  x:     [0.0,0.05,0.02,0.04,0.02,0.00,-0.02,-0.03,-0.03,-0.02,0.00,0.03, 0.0]
#  y:     [0.1,0.10,0.10,0.13,0.13,0.14, 0.13, 0.10, 0.10, 0.13,0.09,0.09, 0.12]
#  theta: [0.0,0.00,0.30,0.00,0.30,0.00, 0.30, 0.00, 0.30, 0.00,0.00,0.00,-0.3]


### foot settings #############################################################

foot:
  size: {x: 0.15, y: 0.081, z: 0.03}
  separation: 0.1
#  origin_shift: {x: 0.02, y: 0.006}
  left: #position of planner foot frame (center of sole) given in robot's "foot" tf frame
    frame_id: /l_sole
    foot_frame:
      {x: 0.02, y: 0.00, z: 0.00, roll: 0.00, pitch: 0.00, yaw: 0.00}
  right:
    frame_id: \r_sole
    foot_frame:
      {x: 0.02, y: 0.00, z: 0.00, roll: 0.00, pitch: 0.00, yaw: 0.00}
  #origin_shift: {x: 0.02, y: 0.006, z: 0.00, roll: 0.00, pitch: 0.00, yaw: 0.00}
  # bounding box of allowed footsteps; refined by the more accurate step range
#  max:
#    step: {x: 0.07, y: 0.15, theta: 0.3}
#    inverse:
#      step: {x: -0.03, y: 0.095, theta: -0.1}

### pelvis pose to feet center (on ground) transform ###########################
pelvis_to_feet_center: {x: 0.0, y: 0.0, z: -0.239}
### step range ################################################################

#step_range:
  #x: [0.00, 0.01, 0.02, 0.03, 0.05, 0.06, 0.07, 0.07,-0.03,-0.03,-0.02,-0.01]
  #y: [0.15, 0.15, 0.15, 0.14, 0.13, 0.13, 0.12, 0.09, 0.09, 0.13, 0.14, 0.15]
